apiVersion: v1
kind: ConfigMap
metadata:
  name: config-env
  namespace: sabino-labs
data:
  ENVIRONMENT: "DEV"
  DEBUG: "True"
  BACKEND_SERVER_HOST: "127.0.0.1"
  BACKEND_SERVER_PORT: "8000"
  BACKEND_SERVER_WORKERS: "4"
  POSTGRES_DB: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_SCHEMA: "postgresql"
  POSTGRES_USERNAME: "postgres"
  IS_ALLOWED_CREDENTIALS: "True"
  API_TOKEN: "YOUR-API-TOKEN"
  AUTH_TOKEN: "YOUR-AUTHENTICATION-TOKEN"
  POSTGRES_HOST: "localhost"
  POSTGRES_URI: '{POSTGRES_SCHEMA}://{POSTGRES_USERNAME}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}'
  DB_TIMEOUT: "5"
  DB_POOL_SIZE: "100"
  DB_MAX_POOL_CON: "80"
  DB_POOL_OVERFLOW: "20"
  IS_DB_ECHO_LOG: "True"
  IS_DB_EXPIRE_ON_COMMIT: "False"
  IS_DB_FORCE_ROLLBACK: "True"
  JWT_SECRET_KEY: "YOUR-JWT-SECRET-KEY"
  JWT_SUBJECT: "YOUR-JWT-SUBJECT"
  JWT_TOKEN_PREFIX: "YOUR-TOKEN-PREFIX"
  JWT_ALGORITHM: "HS256"
  JWT_MIN: "60"
  JWT_HOUR: "23"
  JWT_DAY: "6"
  HASHING_ALGORITHM_LAYER_1: "bcrypt"
  HASHING_ALGORITHM_LAYER_2: "argon2"
  HASHING_SALT: "YOUR-RANDOM-SALTY-SALT"
  CODECOV_TOKEN: ""