version: '3.9'

services:
  postgres_db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata

  web:
    container_name: beer-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
    env_file:
      - ./.env

volumes:
  app-db-data:
