version: '3.9'

services:
  postgresql:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - postgresql_db_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"

  app:
    container_name: beer-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8001:8000"
    depends_on:
      - postgresql

volumes:
  postgresql_db_data:
