apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: beer-api-hpa
  namespace: sabino-labs
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: beer-api
 minReplicas: 1
 maxReplicas: 5
 targetCPUUtilizationPercentage: 70